# Generated by Django 6.1 on 2026-08-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_resource_booking_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availabilities'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='rol',
            new_name='role',
        ),
    ]
